name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Permet de lancer manuellement le workflow depuis l'interface GitHub

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      
    - name: Run tests
      run: mvn test
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-jar
        path: target/*.jar
        retention-days: 1

  docker-build:
    name: Build Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and export Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: projetsimplejava:latest
        
    - name: Test Docker image
      run: docker run --rm projetsimplejava:latest echo "Docker image works!"

  deploy:
    name: Deploy to Render
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to Render
      # Utiliser le hook de déploiement Render
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"key": "${{ secrets.RENDER_DEPLOY_HOOK_KEY }}"}' \
          ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        RENDER_DEPLOY_HOOK_KEY: ${{ secrets.RENDER_DEPLOY_HOOK_KEY }}

    - name: Verify Deployment
      run: |
        echo "Deployment triggered successfully"
        echo "Please check deployment status at https://dashboard.render.com"
