name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Permet de lancer manuellement le workflow depuis l'interface GitHub

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml

  docker-build:
    name: Build Docker Image
    needs: build-and-test
    if: success()
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: |
        docker build -t projetsimplejava:latest .
        echo "Docker image built successfully"

  deploy:
    name: Deploy to Render
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Check for Render deploy secrets
      id: check_secrets
      run: |
        if [[ -n "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" && -n "${{ secrets.RENDER_DEPLOY_HOOK_KEY }}" ]]; then
          echo "render_secrets_available=true" >> $GITHUB_OUTPUT
        else
          echo "render_secrets_available=false" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to Render
      if: steps.check_secrets.outputs.render_secrets_available == 'true'
      run: |
        echo "=== DÉPLOIEMENT VERS RENDER ==="
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"key": "${{ secrets.RENDER_DEPLOY_HOOK_KEY }}"}' \
          ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        echo "🚀 Déploiement déclenché avec succès!"
        echo "Vérifiez le statut sur https://dashboard.render.com"

    - name: Missing configuration
      if: steps.check_secrets.outputs.render_secrets_available != 'true'
      run: |
        echo "⚠️ CONFIGURATION INCOMPLÈTE ⚠️"
        echo "Les secrets Render ne sont pas configurés. Suivez ces instructions :"
        echo "1. Allez dans votre service web sur Render"
        echo "2. Cliquez sur 'Settings' > 'Deploy Hooks'"
        echo "3. Créez un nouveau hook et copiez l'URL générée"
        echo "4. Ajoutez les secrets dans GitHub : Settings > Secrets > Actions"
        echo "   - RENDER_DEPLOY_HOOK_URL : URL complète du webhook"
        echo "   - RENDER_DEPLOY_HOOK_KEY : Partie après ?key= dans l'URL"
        echo ""
        echo "Pour le moment, déployez manuellement : https://dashboard.render.com"
