name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    # Permet de lancer manuellement le workflow depuis l'interface GitHub

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml

  docker-build:
    name: Build Docker Image
    needs: build-and-test
    if: success()
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: |
        docker build -t projetsimplejava:latest .
        echo "Docker image built successfully"

  deploy:
    name: Deploy to Render
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Deployment Information
      run: |
        echo "=== DÉPLOIEMENT SUR RENDER ==="
        echo "⚠️ CONFIGURATION REQUISE ⚠️"
        echo "Pour activer le déploiement automatique, configurez les secrets suivants dans GitHub :"
        echo "1. RENDER_DEPLOY_HOOK_URL : URL du webhook de déploiement Render"
        echo "2. RENDER_DEPLOY_HOOK_KEY : Clé d'authentification pour le webhook"
        echo ""
        echo "Vous pouvez obtenir ces valeurs depuis votre tableau de bord Render :"
        echo "- Allez dans votre service web sur Render"
        echo "- Cliquez sur 'Settings' > 'Deploy Hooks'"
        echo "- Créez un nouveau hook et copiez l'URL générée"
        echo ""
        echo "Une fois ces secrets configurés, le déploiement se fera automatiquement"
        echo "Pour le moment, vous devez déployer manuellement sur Render"
        echo "Visitez : https://dashboard.render.com pour déployer votre application"
